# Generated by Django 4.2.5 on 2023-09-13 17:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='about',
            field=tinymce.models.HTMLField(help_text='Введите сведения об авторе', verbose_name='Сведения об авторе'),
        ),
    ]
