# Generated by Django 4.2.5 on 2023-09-13 17:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_author_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=tinymce.models.HTMLField(help_text='Введите краткое описание книги', max_length=1000, verbose_name='Аннотация книги'),
        ),
    ]
